apiVersion: v1
kind: Service
metadata:
  name: extip-service
spec:
  selector:
    app: hello-world-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  externalIPs:
    - 192.168.100.12
